pipeline {
    agent "ec2-agent-01" 
    stages {
        stage('info') { 
            steps {
                sh(script: """ whoami;pwd;la -al """, lable: "first stage")
            }
        }
    }
}
